//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIDS.MOBILE.APP.PARENTS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIDS.MOBILE.APP.PARENTS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string _00001 {
            get {
                return ResourceManager.GetString("00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _00002 {
            get {
                return ResourceManager.GetString("00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _00003 {
            get {
                return ResourceManager.GetString("00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _00004 {
            get {
                return ResourceManager.GetString("00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string _00005 {
            get {
                return ResourceManager.GetString("00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _00006 {
            get {
                return ResourceManager.GetString("00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account or password incorrect.
        /// </summary>
        internal static string _00007 {
            get {
                return ResourceManager.GetString("00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        internal static string _00008 {
            get {
                return ResourceManager.GetString("00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string _00009 {
            get {
                return ResourceManager.GetString("00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _00010 {
            get {
                return ResourceManager.GetString("00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _00011 {
            get {
                return ResourceManager.GetString("00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out of your account.
        /// </summary>
        internal static string _00012 {
            get {
                return ResourceManager.GetString("00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string _00013 {
            get {
                return ResourceManager.GetString("00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string _00014 {
            get {
                return ResourceManager.GetString("00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string _00015 {
            get {
                return ResourceManager.GetString("00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids profile.
        /// </summary>
        internal static string _00016 {
            get {
                return ResourceManager.GetString("00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string _00017 {
            get {
                return ResourceManager.GetString("00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be null.
        /// </summary>
        internal static string _00018 {
            get {
                return ResourceManager.GetString("00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password do not match.
        /// </summary>
        internal static string _00019 {
            get {
                return ResourceManager.GetString("00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        internal static string _00020 {
            get {
                return ResourceManager.GetString("00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during execution.
        /// </summary>
        internal static string _00021 {
            get {
                return ResourceManager.GetString("00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long .
        /// </summary>
        internal static string _00022 {
            get {
                return ResourceManager.GetString("00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed.
        /// </summary>
        internal static string _00023 {
            get {
                return ResourceManager.GetString("00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string _00024 {
            get {
                return ResourceManager.GetString("00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string _00025 {
            get {
                return ResourceManager.GetString("00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Password.
        /// </summary>
        internal static string _00026 {
            get {
                return ResourceManager.GetString("00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string _00027 {
            get {
                return ResourceManager.GetString("00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password.
        /// </summary>
        internal static string _00028 {
            get {
                return ResourceManager.GetString("00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string _00029 {
            get {
                return ResourceManager.GetString("00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string _00030 {
            get {
                return ResourceManager.GetString("00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string _00031 {
            get {
                return ResourceManager.GetString("00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string _00032 {
            get {
                return ResourceManager.GetString("00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        internal static string _00033 {
            get {
                return ResourceManager.GetString("00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with school.
        /// </summary>
        internal static string _00038 {
            get {
                return ResourceManager.GetString("00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents need to know.
        /// </summary>
        internal static string _00039 {
            get {
                return ResourceManager.GetString("00039", resourceCulture);
            }
        }
    }
}
