//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIDS.MOBILE.APP.PARENTS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIDS.MOBILE.APP.PARENTS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string _00001 {
            get {
                return ResourceManager.GetString("00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _00002 {
            get {
                return ResourceManager.GetString("00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _00003 {
            get {
                return ResourceManager.GetString("00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _00004 {
            get {
                return ResourceManager.GetString("00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string _00005 {
            get {
                return ResourceManager.GetString("00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _00006 {
            get {
                return ResourceManager.GetString("00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account or password incorrect.
        /// </summary>
        internal static string _00007 {
            get {
                return ResourceManager.GetString("00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        internal static string _00008 {
            get {
                return ResourceManager.GetString("00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string _00009 {
            get {
                return ResourceManager.GetString("00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _00010 {
            get {
                return ResourceManager.GetString("00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _00011 {
            get {
                return ResourceManager.GetString("00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out of your account.
        /// </summary>
        internal static string _00012 {
            get {
                return ResourceManager.GetString("00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string _00013 {
            get {
                return ResourceManager.GetString("00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string _00014 {
            get {
                return ResourceManager.GetString("00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string _00015 {
            get {
                return ResourceManager.GetString("00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids profile.
        /// </summary>
        internal static string _00016 {
            get {
                return ResourceManager.GetString("00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string _00017 {
            get {
                return ResourceManager.GetString("00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be null.
        /// </summary>
        internal static string _00018 {
            get {
                return ResourceManager.GetString("00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password do not match.
        /// </summary>
        internal static string _00019 {
            get {
                return ResourceManager.GetString("00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        internal static string _00020 {
            get {
                return ResourceManager.GetString("00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during execution.
        /// </summary>
        internal static string _00021 {
            get {
                return ResourceManager.GetString("00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long .
        /// </summary>
        internal static string _00022 {
            get {
                return ResourceManager.GetString("00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed.
        /// </summary>
        internal static string _00023 {
            get {
                return ResourceManager.GetString("00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string _00024 {
            get {
                return ResourceManager.GetString("00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string _00025 {
            get {
                return ResourceManager.GetString("00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Password.
        /// </summary>
        internal static string _00026 {
            get {
                return ResourceManager.GetString("00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string _00027 {
            get {
                return ResourceManager.GetString("00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password.
        /// </summary>
        internal static string _00028 {
            get {
                return ResourceManager.GetString("00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string _00029 {
            get {
                return ResourceManager.GetString("00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string _00030 {
            get {
                return ResourceManager.GetString("00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string _00031 {
            get {
                return ResourceManager.GetString("00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string _00032 {
            get {
                return ResourceManager.GetString("00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        internal static string _00033 {
            get {
                return ResourceManager.GetString("00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with school.
        /// </summary>
        internal static string _00038 {
            get {
                return ResourceManager.GetString("00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents need to know.
        /// </summary>
        internal static string _00039 {
            get {
                return ResourceManager.GetString("00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string _00040 {
            get {
                return ResourceManager.GetString("00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent Request.
        /// </summary>
        internal static string _00041 {
            get {
                return ResourceManager.GetString("00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Advices.
        /// </summary>
        internal static string _00042 {
            get {
                return ResourceManager.GetString("00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up.
        /// </summary>
        internal static string _00043 {
            get {
                return ResourceManager.GetString("00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Action.
        /// </summary>
        internal static string _00044 {
            get {
                return ResourceManager.GetString("00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string _00045 {
            get {
                return ResourceManager.GetString("00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string _00046 {
            get {
                return ResourceManager.GetString("00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuition Fee.
        /// </summary>
        internal static string _00047 {
            get {
                return ResourceManager.GetString("00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string _00048 {
            get {
                return ResourceManager.GetString("00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        internal static string _00049 {
            get {
                return ResourceManager.GetString("00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodical Reviews.
        /// </summary>
        internal static string _00050 {
            get {
                return ResourceManager.GetString("00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s profile.
        /// </summary>
        internal static string _00051 {
            get {
                return ResourceManager.GetString("00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        internal static string _00052 {
            get {
                return ResourceManager.GetString("00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string _00053 {
            get {
                return ResourceManager.GetString("00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string _00054 {
            get {
                return ResourceManager.GetString("00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string _00055 {
            get {
                return ResourceManager.GetString("00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string _00056 {
            get {
                return ResourceManager.GetString("00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string _00057 {
            get {
                return ResourceManager.GetString("00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        internal static string _00058 {
            get {
                return ResourceManager.GetString("00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string _00059 {
            get {
                return ResourceManager.GetString("00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string _00060 {
            get {
                return ResourceManager.GetString("00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string _00061 {
            get {
                return ResourceManager.GetString("00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful .
        /// </summary>
        internal static string _00062 {
            get {
                return ResourceManager.GetString("00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string _00063 {
            get {
                return ResourceManager.GetString("00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching information of .
        /// </summary>
        internal static string _00079 {
            get {
                return ResourceManager.GetString("00079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL COMPLETED.
        /// </summary>
        internal static string _00080 {
            get {
                return ResourceManager.GetString("00080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEED TO COMPLETE.
        /// </summary>
        internal static string _00081 {
            get {
                return ResourceManager.GetString("00081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        internal static string _00082 {
            get {
                return ResourceManager.GetString("00082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string _00083 {
            get {
                return ResourceManager.GetString("00083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        internal static string _00084 {
            get {
                return ResourceManager.GetString("00084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string _00085 {
            get {
                return ResourceManager.GetString("00085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce.
        /// </summary>
        internal static string _00086 {
            get {
                return ResourceManager.GetString("00086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : .
        /// </summary>
        internal static string _00087 {
            get {
                return ResourceManager.GetString("00087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to complete.
        /// </summary>
        internal static string _00088 {
            get {
                return ResourceManager.GetString("00088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date : .
        /// </summary>
        internal static string _00089 {
            get {
                return ResourceManager.GetString("00089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to .
        /// </summary>
        internal static string _00090 {
            get {
                return ResourceManager.GetString("00090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new message to send to kid&apos;s teacher.
        /// </summary>
        internal static string _00091 {
            get {
                return ResourceManager.GetString("00091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose kids .
        /// </summary>
        internal static string _00092 {
            get {
                return ResourceManager.GetString("00092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing.
        /// </summary>
        internal static string _00093 {
            get {
                return ResourceManager.GetString("00093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose date to send message.
        /// </summary>
        internal static string _00094 {
            get {
                return ResourceManager.GetString("00094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string _00095 {
            get {
                return ResourceManager.GetString("00095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your message..
        /// </summary>
        internal static string _00096 {
            get {
                return ResourceManager.GetString("00096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string _00097 {
            get {
                return ResourceManager.GetString("00097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string _00098 {
            get {
                return ResourceManager.GetString("00098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string _00099 {
            get {
                return ResourceManager.GetString("00099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent with Approved.
        /// </summary>
        internal static string _00100 {
            get {
                return ResourceManager.GetString("00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent without Approved.
        /// </summary>
        internal static string _00101 {
            get {
                return ResourceManager.GetString("00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new leave request.
        /// </summary>
        internal static string _00102 {
            get {
                return ResourceManager.GetString("00102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string _00103 {
            get {
                return ResourceManager.GetString("00103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed.
        /// </summary>
        internal static string _00104 {
            get {
                return ResourceManager.GetString("00104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _00105 {
            get {
                return ResourceManager.GetString("00105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _00106 {
            get {
                return ResourceManager.GetString("00106", resourceCulture);
            }
        }
    }
}
